server:
  port: 8086
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: bot-ingress-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

eureka:
  client:
    enabled: false

app:
  services:
    productivity-url: http://productivity-service:8084
    finance-url: http://finance-service:8083
    routine-url: http://routine-service:8085
