package com.naqashly.auth.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.ZonedDateTime;

/**
 * <h1>User JPA Entity Specification</h1>
 * 
 * <p><b>WHAT:</b> Relational database entity mapping the {@code users} table in PostgreSQL ({@code naqashly_auth_db}).</p>
 * <p><b>WHY:</b> Represents registered platform user accounts, storing credentials, identity provider metadata, and token version numbers for security revoking.</p>
 * <p><b>HOW:</b> Utilizes Jakarta Persistence (JPA) annotations for ORM mapping alongside Lombok annotations for boilerplate generation (getters, setters, builders).</p>
 * 
 * @author Barkat Bashir
 * @version 1.0.0
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * Unique Primary Key ID.
     * <p><b>WHAT:</b> Auto-incrementing 64-bit BigInt sequence generated by PostgreSQL.</p>
     * <p><b>WHY:</b> Serves as the primary identifier across downstream microservices (encoded into JWT {@code sub} claim and {@code X-User-Id} headers).</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User Email Address.
     * <p><b>WHAT:</b> Unique login credential string.</p>
     * <p><b>WHY:</b> Primary key for user authentication lookup and notification delivery.</p>
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * BCrypt Hashed Password.
     * <p><b>WHAT:</b> One-way salted hash generated by BCrypt.</p>
     * <p><b>WHY:</b> Ensures raw passwords are never saved in storage. {@code null} for social OAuth2 users.</p>
     */
    @Column(name = "password_hash")
    private String passwordHash;

    /**
     * Full Display Name.
     * <p><b>WHAT:</b> User's preferred display name.</p>
     * <p><b>WHY:</b> Displayed on dashboard UIs and embedded in JWT claims.</p>
     */
    @Column(nullable = false)
    private String name;

    /**
     * Authentication Provider Enum.
     * <p><b>WHAT:</b> Identifies account creation method ({@link AuthProvider#LOCAL}, {@link AuthProvider#GOOGLE}, {@link AuthProvider#GITHUB}).</p>
     * <p><b>WHY:</b> Determines whether password validation is required during login processing.</p>
     */
    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AuthProvider provider = AuthProvider.LOCAL;

    /**
     * OAuth2 External Provider ID.
     * <p><b>WHAT:</b> Subject identifier returned by external OAuth2 providers (e.g. Google Sub ID).</p>
     */
    @Column(name = "provider_id")
    private String providerId;

    /**
     * Email Verification Status Flag.
     * <p><b>WHAT:</b> Boolean flag confirming if the email address has been validated via link.</p>
     */
    @Builder.Default
    @Column(name = "email_verified", nullable = false)
    private boolean emailVerified = false;

    /**
     * Token Version Counter for Global Session Revocation.
     * <p><b>WHAT:</b> Integer counter incremented whenever all active user refresh tokens must be invalidated.</p>
     * <p><b>WHY:</b> Provides instant global logout across all devices without expensive database session lookups on every API request.</p>
     */
    @Builder.Default
    @Column(name = "token_version", nullable = false)
    private Integer tokenVersion = 1;

    /**
     * Timestamp of Account Creation.
     * <p><b>WHAT:</b> Immutable ISO timestamp recording exact creation time in UTC/Zoned format.</p>
     */
    @Builder.Default
    @Column(name = "created_at", nullable = false, updatable = false)
    private ZonedDateTime createdAt = ZonedDateTime.now();

    /**
     * JPA Lifecycle Callback.
     * <p><b>WHAT:</b> Sets {@code createdAt} timestamp automatically prior to first SQL INSERT statement.</p>
     */
    @PrePersist
    protected void onCreate() {
        createdAt = ZonedDateTime.now();
    }
}
