server:
  port: 8083
  shutdown: graceful

spring:
  springdoc:
    api-docs:
      path: /api/v1/productivity/v3/api-docs
    swagger-ui:
      path: /api/v1/productivity/swagger-ui.html
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: productivity-service
  datasource:
    url: jdbc:postgresql://localhost:5433/naqashly_productivity_db
    username: productivity_user
    password: productivity_password_123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
