server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: finance-service
          uri: lb://FINANCE-SERVICE
          predicates:
            - Path=/api/v1/finance/**

        - id: productivity-service
          uri: lb://PRODUCTIVITY-SERVICE
          predicates:
            - Path=/api/v1/productivity/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
